# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Rcpp function
#' @name gibbsC
#' @description an Rcpp function of gibbs sample
#' @param N sample size
#' @param a The first parameter of the distribution
#' @param b The second parameter of the distribution
#' @param n The third parameter of the distribution
#' @return generated random numbers matrix \code{mat}
#' @examples
#' \dontrun{
#' C <- gibbsC(5000,1,1,25)
#' print(C)
#' }
#' @export
gibbsC <- function(N, a, b, n) {
    .Call('_StatComp21088_gibbsC', PACKAGE = 'StatComp21088', N, a, b, n)
}

